#include "LangInfo.h"

// Order matches wifi_items in ESP32-DIV.ino (all 12 WIFI_FEATURE_COUNT
// entries, spanning both paged-submenu pages -- see WIFI_INFO_COUNT).
const InfoText wifi_page0_info[12] = {
    {"Analyzes network traffic by capturing data packets in the air, allowing you to visualize activity, protocol types, and the volume of information flowing in the environment.",
     "Analisa o trafego da rede capturando pacotes de dados no ar, permitindo visualizar a atividade, os tipos de protocolo e o volume de informacoes trafegadas no ambiente.",
     "Analiza el trafico de la red capturando paquetes de datos en el aire, permitiendo visualizar la actividad, los tipos de protocolo y el volumen de informacion que circula en el entorno."},
    {"Instantly creates dozens of fake Wi-Fi networks, flooding the available connections list on nearby devices with random or custom names.",
     "Cria dezenas de redes Wi-Fi falsas de forma instantanea, inundando a lista de conexoes disponiveis nos dispositivos proximos com nomes aleatorios ou personalizados.",
     "Crea decenas de redes Wi-Fi falsas de forma instantanea, inundando la lista de conexiones disponibles en los dispositivos cercanos con nombres aleatorios o personalizados."},
    {"Disconnects targets from a Wi-Fi network by sending spoofed deauthentication packets, tricking both the router and the device into dropping the connection.",
     "Desconecta alvos de uma rede Wi-Fi enviando pacotes de desautenticacao falsificados, enganando o roteador e o dispositivo para que encerrem a conexao.",
     "Desconecta objetivos de una red Wi-Fi enviando paquetes de desautenticacion falsificados, enganando tanto al router como al dispositivo para que terminen la conexion."},
    {"Sends thousands of mass network search requests to nearby routers, testing the equipment's stability against overload and denial-of-service attacks.",
     "Envia milhares de solicitacoes de busca de rede em massa para roteadores proximos, testando a estabilidade dos equipamentos contra ataques de sobrecarga e negacao de servico.",
     "Envia miles de solicitudes masivas de busqueda de red a routers cercanos, probando la estabilidad de los equipos frente a ataques de sobrecarga y denegacion de servicio."},
    {"Actively listens to the environment for deauthentication packets, acting as an alarm to indicate if any nearby network is under a disconnection attack.",
     "Escuta ativamente o ambiente em busca de pacotes de desautenticacao, servindo como um alarme para indicar se alguma rede proxima esta sofrendo um ataque de desconexao.",
     "Escucha activamente el entorno en busca de paquetes de desautenticacion, funcionando como una alarma para indicar si alguna red cercana esta sufriendo un ataque de desconexion."},
    {"Scans local radio channels to map all Wi-Fi networks and the devices (clients) connected to them, displaying information such as signal strength, channel, and MAC address.",
     "Varre os canais de radio locais para mapear todas as redes Wi-Fi e os dispositivos (clientes) conectados a elas, exibindo informacoes como forca do sinal, canal e endereco MAC.",
     "Recorre los canales de radio locales para mapear todas las redes Wi-Fi y los dispositivos (clientes) conectados a ellas, mostrando informacion como la intensidad de la senal, el canal y la direccion MAC."},
    {"Stands up a fake open network (Evil Twin) that redirects anyone who connects to a controlled login page, used in phishing tests to capture passwords.",
     "Levanta uma rede aberta falsa (Evil Twin) que redireciona qualquer pessoa conectada para uma pagina de login controlada, usada em testes de phishing para capturar senhas.",
     "Levanta una red abierta falsa (Evil Twin) que redirige a cualquier persona conectada a una pagina de inicio de sesion controlada, utilizada en pruebas de phishing para capturar contrasenas."},
    {"Discovers the name of hidden Wi-Fi networks by waiting for or forcing a legitimate device to connect, capturing the network name when association packets are exchanged.",
     "Descobre o nome de redes Wi-Fi ocultas aguardando ou forcando a conexao de um dispositivo legitimo, capturando o nome da rede no momento em que os pacotes de associacao sao trocados.",
     "Descubre el nombre de redes Wi-Fi ocultas esperando o forzando la conexion de un dispositivo legitimo, capturando el nombre de la red en el momento en que se intercambian los paquetes de asociacion."},
    {"Scans nearby networks and lists only the ones with WPS enabled, a legacy pairing feature known for weak PIN implementations that can expose the Wi-Fi password.",
     "Varre as redes proximas e lista apenas as que estao com WPS ativado, um recurso de pareamento antigo conhecido por implementacoes de PIN fracas que podem expor a senha do Wi-Fi.",
     "Recorre las redes cercanas y lista solo las que tienen WPS activado, una funcion de emparejamiento antigua conocida por implementaciones de PIN debiles que pueden exponer la contrasena del Wi-Fi."},
    {"Scans the local network by sending ARP requests to discover active devices, revealing their IP and MAC addresses even if they don't respond to other probes.",
     "Varre a rede local enviando requisicoes ARP para descobrir dispositivos ativos, revelando os enderecos IP e MAC mesmo que eles nao respondam a outras sondagens.",
     "Recorre la red local enviando solicitudes ARP para descubrir dispositivos activos, revelando sus direcciones IP y MAC aunque no respondan a otras sondas."},
    {"Responds to every probe request from nearby devices, impersonating any network they have previously connected to and tricking them into auto-joining a rogue access point.",
     "Responde a todas as solicitacoes de probe de dispositivos proximos, se passando por qualquer rede a que ja se conectaram antes, enganando-os para que se conectem automaticamente a um ponto de acesso falso.",
     "Responde a todas las solicitudes de probe de dispositivos cercanos, haciendose pasar por cualquier red a la que ya se hayan conectado antes, enganandolos para que se conecten automaticamente a un punto de acceso falso."},
    {"Displays a live bar graph of signal activity across all 2.4GHz channels, helping identify which channels are the most crowded or have the least interference.",
     "Exibe um grafico de barras em tempo real da atividade de sinal em todos os canais de 2.4GHz, ajudando a identificar quais canais estao mais congestionados ou tem menos interferencia.",
     "Muestra un grafico de barras en tiempo real de la actividad de senal en todos los canales de 2.4GHz, ayudando a identificar que canales estan mas congestionados o tienen menos interferencia."},
};

// Order matches bluetooth_items in ESP32-DIV.ino (all 9 BT_FEATURE_COUNT
// entries -- see BT_INFO_COUNT).
const InfoText bluetooth_page0_info[9] = {
    {"Floods the Bluetooth spectrum attempting to disrupt and block nearby connections.",
     "Inunda o espectro Bluetooth para tentar interromper e bloquear conexoes proximas.",
     "Inunda el espectro Bluetooth intentando interrumpir y bloquear las conexiones cercanas."},
    {"Spoofs Bluetooth device identifications to impersonate other devices.",
     "Falsifica identificacoes de dispositivos Bluetooth para se passar por outros aparelhos.",
     "Falsifica identificaciones de dispositivos Bluetooth para hacerse pasar por otros aparatos."},
    {"Sends malformed packets aimed at crashing or generating constant pairing notifications on nearby Apple devices.",
     "Envia pacotes malformados com o objetivo de travar ou gerar notificacoes de pareamento constantes em dispositivos Apple proximos.",
     "Envia paquetes malformados con el objetivo de bloquear o generar notificaciones de emparejamiento constantes en dispositivos Apple cercanos."},
    {"Emulates an Apple AirTag signal, creating fake trackers visible to iPhones in the area.",
     "Emula o sinal de um Apple AirTag, criando rastreadores falsos visiveis para iPhones na area.",
     "Emula la senal de un Apple AirTag, creando rastreadores falsos visibles para los iPhones en el area."},
    {"Scans the area to detect, list, and track the presence of legitimate Apple AirTags around you.",
     "Varre a area para detectar, listar e rastrear a presenca de Apple AirTags legitimos ao redor.",
     "Recorre el area para detectar, listar y rastrear la presencia de Apple AirTags legitimos alrededor."},
    {"Captures raw data packets for monitoring and technical analysis of local traffic.",
     "Captura pacotes brutos de dados para monitoramento e analise tecnica do trafego local.",
     "Captura paquetes de datos en bruto para monitoreo y analisis tecnico del trafico local."},
    {"Lists active Bluetooth Low Energy (BLE) devices in the area, displaying MAC addresses and signal strength.",
     "Lista os dispositivos Bluetooth Low Energy (BLE) ativos na area, exibindo enderecos MAC e a intensidade do sinal.",
     "Lista los dispositivos Bluetooth Low Energy (BLE) activos en el area, mostrando direcciones MAC e intensidad de senal."},
    {"Emulates a keyboard via Bluetooth connection to rapidly inject automated commands and scripts into the target device.",
     "Emula um teclado via conexao Bluetooth para injetar comandos automaticos e scripts rapidamente no aparelho alvo.",
     "Emula un teclado mediante conexion Bluetooth para inyectar comandos automatizados y scripts rapidamente en el dispositivo objetivo."},
    {"Scans the area for Bluetooth signal patterns typical of hidden card skimmers (e.g. on ATMs or gas pumps), alerting you if a likely skimmer device is detected nearby.",
     "Varre a area em busca de padroes de sinal Bluetooth tipicos de skimmers escondidos (por exemplo em caixas eletronicos ou bombas de combustivel), alertando se um provavel skimmer for detectado por perto.",
     "Recorre el area en busca de patrones de senal Bluetooth tipicos de skimmers ocultos (por ejemplo en cajeros automaticos o surtidores de combustible), alertando si se detecta un probable skimmer cerca."},
};

// Order matches nrf_submenu_items in ESP32-DIV.ino, skipping "Back to Main Menu".
const InfoText nrf_info[6] = {
    {"Performs a general scan to find devices operating and emitting signals on the configured radio frequency.",
     "Faz uma varredura geral para encontrar dispositivos operando e emitindo sinais na frequencia de radio configurada.",
     "Realiza un escaneo general para encontrar dispositivos que operan y emiten senales en la frecuencia de radio configurada."},
    {"Attempts to drop or disrupt communication of specific wireless radio protocols.",
     "Tenta derrubar ou interromper a comunicacao de protocolos especificos de radio sem fio.",
     "Intenta derribar o interrumpir la comunicacion de protocolos especificos de radio inalambrica."},
    {"Captures Enhanced ShockBurst protocol packets, widely used in wireless mouse and keyboard communications.",
     "Captura pacotes do protocolo Enhanced ShockBurst, muito utilizado na comunicacao de mouses e teclados sem fio.",
     "Captura paquetes del protocolo Enhanced ShockBurst, muy utilizado en la comunicacion de mouses y teclados inalambricos."},
    {"Resends previously captured ESB packets to repeat the legitimate command of a keyboard or mouse.",
     "Reenvia pacotes ESB capturados anteriormente para repetir o comando legitimo de um teclado ou mouse.",
     "Reenvia paquetes ESB capturados previamente para repetir el comando legitimo de un teclado o mouse."},
    {"Actively searches for 2.4GHz wireless mice and keyboards that have known vulnerabilities (MouseJack flaw).",
     "Procura ativamente por mouses e teclados sem fio de 2.4GHz que possuam vulnerabilidades conhecidas (falha MouseJack).",
     "Busca activamente mouses y teclados inalambricos de 2.4GHz que tengan vulnerabilidades conocidas (fallo MouseJack)."},
    {"Exploits found flaws in wireless peripherals to remotely inject malicious keystrokes into the victim's computer.",
     "Explora as falhas encontradas em perifericos sem fio para injetar digitacao maliciosa remotamente no computador da vitima.",
     "Explota las fallas encontradas en perifericos inalambricos para inyectar remotamente pulsaciones maliciosas en el ordenador de la victima."},
};

// Order matches subghz_submenu_items in ESP32-DIV.ino, skipping "Back to Main Menu".
const InfoText subghz_info[5] = {
    {"Records a captured radio signal (like an alarm or gate remote) and transmits it again to trigger the system.",
     "Grava um sinal de radio capturado (como o de um alarme ou controle de portao) e o transmite novamente para acionar o sistema.",
     "Graba una senal de radio capturada (como la de una alarma o un control de porton) y la transmite nuevamente para activar el sistema."},
    {"Generates intentional noise on frequencies below 1GHz to block the reception of remote control and alarm signals.",
     "Gera ruido intencional em frequencias abaixo de 1GHz para bloquear a recepcao de sinais de controles remotos e alarmes.",
     "Genera ruido intencional en frecuencias por debajo de 1GHz para bloquear la recepcion de senales de controles remotos y alarmas."},
    {"Attempts to guess the code of older radio receivers (like DIP switch gates) by generating and transmitting continuous brute-force sequences.",
     "Tenta adivinhar o codigo de receptores de radio antigos (como portoes de chave DIP) gerando e transmitindo sequencias continuas de forca bruta.",
     "Intenta adivinar el codigo de receptores de radio antiguos (como portones de llave DIP) generando y transmitiendo secuencias continuas de fuerza bruta."},
    {"Listens to the environment to passively identify if there is any signal jamming device operating in the area.",
     "Escuta o ambiente para identificar de forma passiva se existe algum aparelho bloqueador de sinal operando na area.",
     "Escucha el entorno para identificar de forma pasiva si hay algun dispositivo bloqueador de senal operando en el area."},
    {"Allows you to access and transmit radio signals you had previously saved to the memory card.",
     "Permite acessar e transmitir os sinais de radio que voce ja havia salvo no cartao de memoria.",
     "Permite acceder y transmitir las senales de radio que ya habias guardado en la tarjeta de memoria."},
};

// Order matches tools_submenu_items in ESP32-DIV.ino, skipping "Back to Main Menu".
const InfoText tools_info[4] = {
    {"Shows the logs, debugging info, and internal system messages of the device directly on its own screen.",
     "Mostra os logs, informacoes de debug e as mensagens do sistema interno do aparelho diretamente na propria tela.",
     "Muestra los registros, informacion de depuracion y los mensajes del sistema interno del dispositivo directamente en su propia pantalla."},
    {"Allows you to update or reinstall the device's operating system by executing the update file directly from the SD card.",
     "Permite atualizar ou reinstalar o sistema operacional do aparelho executando o arquivo de atualizacao direto pelo cartao SD.",
     "Permite actualizar o reinstalar el sistema operativo del dispositivo ejecutando el archivo de actualizacion directamente desde la tarjeta SD."},
    {"Launches the calibration screen to readjust the precision and alignment of the display's touchscreen function.",
     "Inicia a tela de calibracao para reajustar a precisao e o alinhamento da funcao touchscreen do visor.",
     "Inicia la pantalla de calibracion para reajustar la precision y la alineacion de la funcion tactil de la pantalla."},
    {"Opens an internal folder explorer so you can navigate, view, or delete captures and files stored on the memory card.",
     "Abre um explorador interno de pastas para que voce possa navegar, visualizar ou excluir as capturas e arquivos armazenados no cartao de memoria.",
     "Abre un explorador interno de carpetas para que puedas navegar, visualizar o eliminar las capturas y archivos almacenados en la tarjeta de memoria."},
};

// Order matches rfid_submenu_items in ESP32-DIV.ino, skipping "Back to Main Menu".
const InfoText rfid_info[8] = {
    {"Scans proximity cards or tags to display their open data and Unique Identification (UID) number.",
     "Escaneia cartoes ou tags de aproximacao para exibir seus dados abertos e o numero de identificacao unico (UID).",
     "Escanea tarjetas o tags de proximidad para mostrar sus datos abiertos y el numero de identificacion unico (UID)."},
    {"Copies the extracted data from an original card directly onto a compatible and rewritable blank card.",
     "Copia os dados extraidos de um cartao original diretamente para um cartao virgem compativel e regravavel.",
     "Copia los datos extraidos de una tarjeta original directamente a una tarjeta en blanco compatible y regrabable."},
    {"Formats and completely erases all data written on a rewritable card or tag.",
     "Formata e apaga completamente todos os dados gravados em um cartao ou tag regravavel.",
     "Formatea y borra por completo todos los datos grabados en una tarjeta o tag regrabable."},
    {"Deeply extracts and saves the entire block and sector structure of the card's memory to a file on the SD.",
     "Extrai de forma profunda e salva toda a estrutura de blocos e setores da memoria do cartao em um arquivo no SD.",
     "Extrae en profundidad y guarda toda la estructura de bloques y sectores de la memoria de la tarjeta en un archivo en la SD."},
    {"Uses known key dictionaries to attempt cracking the security of protected access cards to read their content.",
     "Usa dicionarios de chaves conhecidas para tentar quebrar a seguranca de cartoes de acesso protegidos para conseguir ler seu conteudo.",
     "Usa diccionarios de claves conocidas para intentar romper la seguridad de tarjetas de acceso protegidas y poder leer su contenido."},
    {"Emits continuous noise to temporarily interfere with the operation of a physical wall reader.",
     "Emite ruido continuo para interferir temporariamente no funcionamento de um leitor fisico de parede.",
     "Emite ruido continuo para interferir temporalmente en el funcionamiento de un lector fisico de pared."},
    {"Causes purposeful instability in the communication between the tag and the reader, corrupting the reading momentarily.",
     "Causa instabilidade proposital na comunicacao entre a tag e o leitor, corrompendo a leitura momentaneamente.",
     "Provoca inestabilidad intencional en la comunicacion entre el tag y el lector, corrompiendo la lectura momentaneamente."},
    {"Works by emulating a virtual card while simultaneously applying interference techniques against the target reader.",
     "Funciona emulando um cartao virtual e, simultaneamente, aplica tecnicas de interferencia contra o leitor alvo.",
     "Funciona emulando una tarjeta virtual mientras aplica simultaneamente tecnicas de interferencia contra el lector objetivo."},
};

// Order matches gps_submenu_items in ESP32-DIV.ino, skipping "Back to Main Menu".
const InfoText gps_info[2] = {
    {"Associates a wireless network scan with location data obtained from the GPS module, mapping and saving the networks geographically to the SD card.",
     "Associa uma varredura de redes sem fio com os dados de localizacao obtidos do modulo GPS, mapeando e salvando as redes geograficamente no cartao SD.",
     "Asocia un escaneo de redes inalambricas con los datos de ubicacion obtenidos del modulo GPS, mapeando y guardando las redes geograficamente en la tarjeta SD."},
    {"Checks the current reception of the attached GPS module, showing how many satellites are visible to ensure location accuracy.",
     "Verifica a recepcao atual do modulo GPS acoplado, mostrando quantos satelites estao visiveis para garantir a precisao da localizacao.",
     "Verifica la recepcion actual del modulo GPS conectado, mostrando cuantos satelites estan visibles para garantizar la precision de la ubicacion."},
};

// Order matches ir_submenu_items in ESP32-DIV.ino, skipping "Back to Main Menu".
const InfoText ir_info[4] = {
    {"Reads, identifies, and records the infrared signal code of any remote control pointed at the device's sensor.",
     "Le, identifica e grava o codigo do sinal infravermelho de qualquer controle remoto que for apontado para o sensor do aparelho.",
     "Lee, identifica y graba el codigo de la senal infrarroja de cualquier control remoto apuntado hacia el sensor del dispositivo."},
    {"Loads saved infrared signal profiles so you can retransmit them.",
     "Carrega perfis de sinais infravermelhos salvos para que voce possa retransmiti-los.",
     "Carga perfiles de senales infrarrojas guardadas para que puedas retransmitirlas."},
    {"Fires power-off codes in rapid succession to attempt shutting down various generic TV brands at once.",
     "Dispara codigos de desligamento em sequencia rapida para tentar desligar diversas marcas genericas de televisao de uma so vez.",
     "Dispara codigos de apagado en sucesion rapida para intentar apagar varias marcas genericas de televisores a la vez."},
    {"Transmits a bank of generic commands to attempt controlling or shutting down different brands of air conditioners.",
     "Transmite um banco de comandos genericos para tentar controlar ou desligar diferentes marcas de aparelhos de ar-condicionado.",
     "Transmite un banco de comandos genericos para intentar controlar o apagar diferentes marcas de aparatos de aire acondicionado."},
};
